/*
** EPITECH PROJECT, 2026
** rtype
** File description:
** SpirvTests
*/

#include <gtest/gtest.h>

#include <cstdint>
#include <filesystem>
#include <fstream>
#include <iterator>
#include <span>
#include <string>
#include <vector>

#include "render/vulkan/exceptions/ShaderException.hpp"
#include "render/vulkan/pipeline/Spirv.hpp"
#include "test.vert.h"  // Generated by the glsl.spirv rule from shaders/test.vert.

namespace {

namespace pipeline = rtype::render::vulkan::pipeline;
using rtype::render::vulkan::exceptions::ShaderException;

/// @brief A file in the temporary directory, removed when the object is destroyed.
class TemporaryFile {
  public:
    explicit TemporaryFile(const std::string& name)
        : _path{std::filesystem::temp_directory_path() / ("rtype-spirv-tests-" + name)} {}
    ~TemporaryFile() {
        std::error_code error;
        std::filesystem::remove(_path, error);
    }
    TemporaryFile(const TemporaryFile&) = delete;
    TemporaryFile& operator=(const TemporaryFile&) = delete;
    TemporaryFile(TemporaryFile&&) = delete;
    TemporaryFile& operator=(TemporaryFile&&) = delete;

    [[nodiscard]] const std::filesystem::path& getPath() const noexcept { return _path; }

    /// @brief Replaces the file's content with @p bytes.
    void write(const std::vector<char>& bytes) const {
        std::ofstream file{_path, std::ios::binary};
        file.write(bytes.data(), static_cast<std::streamsize>(bytes.size()));
    }

  private:
    std::filesystem::path _path;  ///< Removed on destruction.
};

/// @return The bytes of @p words, in memory order.
std::vector<char> toBytes(std::span<const std::uint32_t> words) {
    const auto* const begin = static_cast<const char*>(static_cast<const void*>(words.data()));
    return {begin, std::next(begin, static_cast<std::ptrdiff_t>(words.size_bytes()))};
}

}  // namespace

TEST(Spirv, EmbeddedShaderIsSpirv) {
    const std::span<const std::uint32_t> code{rtype_shader_test_vert};
    ASSERT_FALSE(code.empty());
    EXPECT_EQ(code.front(), pipeline::kSpirvMagic);
    EXPECT_NO_THROW(pipeline::validateSpirv(code, "test.vert"));
}

TEST(Spirv, ValidateRejectsEmptyAndNonSpirv) {
    EXPECT_THROW(pipeline::validateSpirv({}, "empty"), ShaderException);
    const std::vector<std::uint32_t> notSpirv{0xDEADBEEF, 0};
    EXPECT_THROW(pipeline::validateSpirv(notSpirv, "garbage"), ShaderException);
}

TEST(Spirv, ReadsBackAWrittenModule) {
    const TemporaryFile file{"valid.spv"};
    file.write(toBytes(rtype_shader_test_vert));
    const std::vector<std::uint32_t> code = pipeline::readSpirv(file.getPath());
    EXPECT_EQ(code, std::vector<std::uint32_t>(std::begin(rtype_shader_test_vert), std::end(rtype_shader_test_vert)));
}

TEST(Spirv, RejectsMissingFile) {
    EXPECT_THROW((void)pipeline::readSpirv(std::filesystem::temp_directory_path() / "rtype-spirv-tests-missing.spv"),
                 ShaderException);
}

TEST(Spirv, RejectsSizeNotMultipleOfFour) {
    const TemporaryFile file{"truncated.spv"};
    std::vector<char> bytes = toBytes(rtype_shader_test_vert);
    bytes.pop_back();
    file.write(bytes);
    EXPECT_THROW((void)pipeline::readSpirv(file.getPath()), ShaderException);
}

TEST(Spirv, RejectsWrongMagic) {
    const TemporaryFile file{"text.spv"};
    file.write({'#', 'v', 'e', 'r', 's', 'i', 'o', 'n'});  // GLSL source instead of SPIR-V.
    EXPECT_THROW((void)pipeline::readSpirv(file.getPath()), ShaderException);
}
