target("vulkan-tests")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_deps("render-vulkan")
    add_files("*.cpp", "../main.cpp")
    add_packages("gtest")
    add_tests("default")
