target("vulkan-tests")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_deps("render-vulkan", "engine-core")
    add_files("*.cpp", "../main.cpp")
    -- A test shader, embedded by the same rule as the renderer's built-in shaders.
    add_rules("glsl.spirv")
    add_files("shaders/*.vert")
    add_packages("gtest", "glslang")
    add_tests("default")
