add_requires("gtest")

target("luau-tests")
    set_kind("binary")
    set_default(false)
    set_group("tests")
    add_deps("luau")
    add_files("*.cpp", "../main.cpp")
    add_packages("gtest")
    add_tests("default")
